echo"<p>Installing View Panel is an easy 4 step process (and one of those is just clicking a button!). Please make sure you fill out all the fields and enter the correct information.</p>";
echo"<h1><strong>Step 1 - Database Settings</strong></h1>";
echo"<form id='form1' name='form1' method='post' action='databaseconnect.php'>";
echo"  <table width='722' border='3'>";
echo"    <tr>";
echo"      <td width='357'><p>Local Database Location</p>";
echo"      <p>This is the location of the database. It's usually 'localhost'.</p></td>";
echo"      <td width='313'><label>";
echo"        <input name='localdatabase' type='text' id='localdatabase' value='localhost' size='50' />";
echo"      </label></td>";
echo"    </tr>";
echo"    <tr>";
echo"      <td><p>Database Name</p>";
echo"      <p>Enter the name of the database you've created which VP should use.</p></td>";
echo"      <td><input name='dbname' type='text' id='dbname' value='my_db' size='50' /></td>";
echo"    </tr>";
echo"    <tr>";
echo"      <td>MySQL Username</td>";
echo"      <td><input name='dbuser' type='text' id='dbuser' value='username' size='50' /></td>";
echo"    </tr>";
echo"    <tr>";
echo"      <td>MySQL Password</td>";
echo"      <td><input name='dbpass' type='password' id='dbpass' size='50' /></td>";
echo"    </tr>";
echo"    <tr>";
echo"      <td>Confirm MySQL Password</td>";
echo"      <td><label>";
echo"        <input name='confpass' type='password' id='confpass' size='50' />";
echo"      </label></td>";
echo"    </tr>";
echo"  </table>";
echo"  <h1>Step 2 - Other Settings</h1>";
echo"  <table width='722' border='3'>";
echo"    <tr>";
echo"      <td><p>Time Offset</p>";
echo"      <p>When you make a post into your blog a time will be posted with it.      </p></td>";
echo"      <td><label>";
echo"     <select name='timeoffset' id='timeoffset'>";
echo"          <option value='-39600'>GMT - 11</option>";
echo"          <option value='-36000'>GMT - 10</option>";
echo"          <option value='-32400'>GMT - 9</option>";
echo"          <option value='-28800'>GMT - 8</option>";
echo"          <option value='-25200'>GMT - 7</option>";
echo"          <option value='-21600'>GMT - 6</option>";
echo"          <option value='-18000'>GMT - 5</option>";
echo"          <option value='-14400'>GMT - 4</option>";
echo"          <option value='-10800'>GMT - 3</option>";
echo"          <option value='-7200'>GMT - 2</option>";
echo"          <option value='-3600'>GMT - 1</option>";
echo"          <option value='0'>GMT </option>";
echo"          <option value='3600'>GMT + 1</option>";
echo"          <option value='7200'>GMT + 2</option>";
echo"          <option value='10800'>GMT + 3</option>";
echo"          <option value='14400'>GMT + 4</option>";
echo"          <option value='18000'>GMT + 5</option>";
echo"          <option value='21600'>GMT + 6</option>";
echo"          <option value='25200'>GMT + 7</option>";
echo"          <option value='28800'>GMT + 8</option>";
echo"          <option value='32400'>GMT + 9</option>";
echo"          <option value='36000'>GMT + 10</option>";
echo"          <option value='39600'>GMT + 11</option>";
echo"          <option value='43200'>GMT + 12</option>";
echo"          <option value='46800'>GMT + 13</option>";
echo"          <option value='50400'>GMT + 14</option>";
echo"        </select>";
echo"      </label></td>";
echo"    </tr>";
echo"    <tr>";
echo"      <td><p>Site URL</p>";
echo"        <p>This is the URL of the website you're going to be using View Panel with. If you don't know yet (like you're waiting on View Panel to make the website) just leave it as you can always change it later.</p></td>";
echo"      <td><label>";
echo"        <input name='siteurl' type='text' id='siteurl' size='50' />";
echo"      </label></td>";
echo"    </tr>";
echo"  </table>";
echo"  <h1><strong>Step 3 -The Table</strong> (Blog)</h1>";
echo"  <p>A table will need to be created store all the posts you make. You can create more later.</p>";
echo"  <table width='686' border='1'>";
echo"    <tr>";
echo"      <td width='358'><p>Enter A Blog Name</p></td>";
echo"      <td width='312'><input name='tablename' type='text' id='tablename' value='Happy Blog Time' size='50' /></td>";
echo"    </tr>";
echo"    <tr>";
echo"      <td><p>Enter A Blog Description</p></td>";
echo"      <td><input name='tabledesc' type='text' id='tabledesc' value='It's happy time.' size='50' /></td>";
echo"    </tr>";
echo"  </table>";
echo"  <h1>Step 4 - Create</h1>";
echo"  <p>Hit the submit button to set up everything. It may take anything up to a few minutes. If something goes wrong an error will be returned and you'll have to click the 'back' button in your browser to come back to this page.</p>";
echo"  <p>";
echo"    <label>";
echo"      <input type='submit' name='submit' id='submit' value='Submit' />";
echo"    </label>";
echo"  </p>";
echo"  <p>&nbsp;</p>";
echo"</form>";
